# Generated by Django 3.0.4 on 2020-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='fb_likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cast',
            name='Remuneration',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='no_of_facebook_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='result',
            field=models.CharField(choices=[('Block Buster', 'B'), ('Average', 'A'), ('Disaster', 'D')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='is_debut_movie',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
