# Generated by Django 3.0.4 on 2020-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_auto_20200318_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='fb_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_users_voted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(null=True),
        ),
    ]
