# Generated by Django 3.0.4 on 2020-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0004_auto_20200318_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
