# Generated by Django 3.0.4 on 2020-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_auto_20200318_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='fb_likes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='no_of_facebook_likes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fb_likes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
